## Лабораторна робота 1.
Вступ до машинного навчання. Елементи лінійної алгебри.
1. Лабораторна робота здається у вигляді файла jupyter notebook .ipynb або файлу 
Colab.
2. Назва лабораторної роботи – Прізвище_пр_номер.ipynb
3. Номер варіанту відповідає номеру в Мія.
4. Перед виконанням Обов’язково! Пишіть назву завдання у вигляді коментаря!
Завдання без умови не перевіряються.
5. Кожне завдання виконується в окремому рядку.
6. В кінці лабораторної роботи обов’язково зробити Висновок у вигляді коментаря.
7. Також обов’язково зробити репозиторій на GitHub «Машинне навчання». (Профіль 
на GitHub містить ваше прізвище). І разом із файлом надсилати посилання на гітхаб 
на відповідний файл.

Завдання 13

In [1]:
import numpy as np

1. Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в 
діапазоні від 0 до 1 та знайдіть їх добуток.


In [2]:
# Створення матриць
matrix_2x2_a = np.random.rand(2, 2)
matrix_2x2_b = np.random.rand(2, 2)

In [3]:
# Обчислення добутку
product_2x2 = np.dot(matrix_2x2_a, matrix_2x2_b)
print("Матриця A:\n", matrix_2x2_a)
print("Матриця B:\n", matrix_2x2_b)
print("Добуток матриць A і B:\n", product_2x2)

Матриця A:
 [[0.50832568 0.21483748]
 [0.73641768 0.55661629]]
Матриця B:
 [[0.17787492 0.11563052]
 [0.48154371 0.6846569 ]]
Добуток матриць A і B:
 [[0.19387203 0.20586793]
 [0.39902531 0.46624354]]


2. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в 
діапазоні від -5 до 5 та знайдіть їх добуток.

In [4]:

matrix_3x3_a = np.random.randint(-5, 6, (3, 3))
matrix_3x3_b = np.random.randint(-5, 6, (3, 3))


In [5]:

product_3x3 = np.dot(matrix_3x3_a, matrix_3x3_b)
print("Матриця A:\n", matrix_3x3_a)
print("Матриця B:\n", matrix_3x3_b)
print("Добуток матриць A і B:\n", product_3x3)

Матриця A:
 [[-3 -5  1]
 [-1  4 -5]
 [ 0  2 -1]]
Матриця B:
 [[ 0  2  3]
 [-1 -5 -2]
 [-2  4 -2]]
Добуток матриць A і B:
 [[  3  23  -1]
 [  6 -42  -1]
 [  0 -14  -2]]


3. Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в 
діапазоні від -1 до 1 та знайдіть їх добуток.

In [6]:

matrix_4x4_a = np.random.uniform(-1, 1, (4, 4))
matrix_4x4_b = np.random.uniform(-1, 1, (4, 4))

In [7]:
product_4x4 = np.dot(matrix_4x4_a, matrix_4x4_b)
print("Матриця A:\n", matrix_4x4_a)
print("Матриця B:\n", matrix_4x4_b)
print("Добуток матриць A і B:\n", product_4x4)

Матриця A:
 [[ 0.343008   -0.29115667  0.82350116  0.47282168]
 [-0.500256   -0.36531105  0.00703337  0.07821815]
 [-0.94846859 -0.3911988  -0.46825883  0.56378692]
 [-0.89930825 -0.15569375 -0.79474277  0.20826865]]
Матриця B:
 [[ 0.24051117  0.30007396  0.78100186 -0.65062716]
 [-0.49729609  0.23254254  0.27823793  0.90978015]
 [ 0.77134942 -0.66863482  0.4907368  -0.32588253]
 [ 0.59324368  0.31243752  0.66976474  0.94174579]]
Добуток матриць A і B:
 [[ 1.14299394 -0.36767286  0.90768067 -0.31114569]
 [ 0.1131782  -0.21532863 -0.43650497  0.06449696]
 [-0.06030381  0.11366125 -0.70178932  0.94473585]
 [-0.6283381   0.29039922 -0.99619985  0.89859619]]


4. Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в 
діапазоні від 1 до 10 та знайдіть суму їх елементів.

In [8]:
matrix_5x5_a = np.random.randint(1, 11, (5, 5))
matrix_5x5_b = np.random.randint (1, 11, (5, 5))

In [9]:
sum_5x5 = np.sum(matrix_5x5_a) + np.sum(matrix_5x5_b)
print("Матриця A:\n", matrix_5x5_a)
print("Матриця B:\n", matrix_5x5_b)
print("Сума елементів матриць A і B:", sum_5x5)

Матриця A:
 [[10  3  1  7  6]
 [ 6  5  5  1  8]
 [ 6  4  5 10  4]
 [10  9  3  8  1]
 [10  1  8 10  7]]
Матриця B:
 [[4 6 4 2 9]
 [2 3 2 3 1]
 [1 7 2 8 9]
 [2 7 7 5 6]
 [3 4 2 7 4]]
Сума елементів матриць A і B: 258


5. Створіть дві матриці розміром 6x6, заповніть їх випадковими дійсними числами в 
діапазоні від 0 до 1 та знайдіть різницю їх елементів.

In [10]:
matrix_6x6_a = np.random.rand(6, 6)
matrix_6x6_b = np.random.rand(6, 6)

In [11]:
difference_6x6 = matrix_6x6_a - matrix_6x6_b
print("Матриця A:\n", matrix_6x6_a)
print("Матриця B:\n", matrix_6x6_b)
print("Різниця матриць A і B:\n", difference_6x6)

Матриця A:
 [[0.77476307 0.00633757 0.07751934 0.22928652 0.19915106 0.73323727]
 [0.92511635 0.81121076 0.57920378 0.02507462 0.38686376 0.24883386]
 [0.40121951 0.81113452 0.26483968 0.99200977 0.58660437 0.63564442]
 [0.15762096 0.04615789 0.13529522 0.3111777  0.00541934 0.20532201]
 [0.50474633 0.67761816 0.31511328 0.73513159 0.90977077 0.09109231]
 [0.59347612 0.27950515 0.95102753 0.15465155 0.58396568 0.6027152 ]]
Матриця B:
 [[0.24423384 0.7439393  0.84836683 0.38224363 0.57522666 0.20625068]
 [0.58516941 0.64554065 0.39365858 0.52393943 0.87978751 0.36794432]
 [0.12773658 0.56641783 0.89389679 0.30642067 0.76609842 0.95491637]
 [0.13378154 0.30780634 0.42756288 0.00409467 0.23848907 0.40152714]
 [0.93970773 0.42539351 0.17670755 0.76536572 0.27580108 0.6627413 ]
 [0.64305836 0.2278067  0.91367312 0.32443612 0.82335126 0.8960104 ]]
Різниця матриць A і B:
 [[ 0.53052923 -0.73760173 -0.77084749 -0.15295711 -0.37607559  0.52698659]
 [ 0.33994694  0.16567011  0.18554521 -0.498864

6. Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в 
діапазоні від -10 до 10 та знайдіть суму їх елементів

In [12]:
matrix_7x7_a = np.random.randint(-10, 11, (7, 7))
matrix_7x7_b = np.random.randint(-10, 11, (7, 7))

In [13]:
sum_7x7 = np.sum(matrix_7x7_a) + np.sum(matrix_7x7_b)
print("Матриця A:\n", matrix_7x7_a)
print("Матриця B:\n", matrix_7x7_b)
print("Сума елементів матриць A і B:", sum_7x7)

Матриця A:
 [[ -3   9  -1   9  -4   7  -6]
 [ 10   6  -5  -6  -8  -7  -3]
 [ -9  -1   1   2  -3  -9   7]
 [  7  -3  -9  -5   3  -9   2]
 [ -1  -3  -7  -1  -3  -9   8]
 [ -8   0   4   3  -6  10   3]
 [  1  10   6   6   7 -10   4]]
Матриця B:
 [[ 10  -2   1   9   3  -4  -4]
 [ -2   5  -5   3   3   5  -1]
 [  8  -4 -10   5  -2   4   2]
 [  6   0  -5   5  -8  -9   2]
 [  5  -3  -1 -10   1   6 -10]
 [ -4   5   4  10  -2  -3   2]
 [ -1   6  -6  -8   3  -2  -8]]
Сума елементів матриць A і B: -15


7. Створіть дві матриці розміром 8x8, заповніть їх випадковими дійсними числами в 
діапазоні від -1 до 1 та знайдіть різницю їх елементів.

In [14]:
matrix_8x8_a = np.random.uniform(-1, 1, (8, 8))
matrix_8x8_b = np.random.uniform(-1, 1, (8, 8))

In [15]:
difference_8x8 = matrix_8x8_a - matrix_8x8_b
print("Матриця A:\n", matrix_8x8_a)
print("Матриця B:\n", matrix_8x8_b)
print("Різниця матриць A і B:\n", difference_8x8)

Матриця A:
 [[ 0.87968329 -0.62095211  0.90480153  0.69722587  0.19467559 -0.3751697
   0.22991366  0.37984353]
 [ 0.08274348 -0.83338987  0.66733252 -0.56245669  0.88089433 -0.64910347
   0.92308818  0.6718973 ]
 [ 0.52483174 -0.24606889 -0.61509749  0.78363249 -0.53505318  0.04476224
   0.7355531  -0.38324632]
 [-0.49763293 -0.49065084  0.33617506  0.35968071 -0.78715221  0.53122716
   0.4998063  -0.71661717]
 [-0.24061569 -0.79052092 -0.90656711  0.26117451  0.93061308 -0.0322186
  -0.88949587  0.10484583]
 [-0.94113112 -0.32978881 -0.68843227 -0.71013005  0.69724619 -0.92017156
   0.05825901 -0.4542631 ]
 [-0.10460374 -0.51445012  0.61381015  0.72157648 -0.40301152 -0.79634842
  -0.29063334  0.36071191]
 [ 0.30296621 -0.97788267  0.75534592 -0.53251889  0.01816001  0.51480939
  -0.07588561 -0.62615876]]
Матриця B:
 [[-0.37808704  0.16610172  0.96425841  0.47365527 -0.08796384 -0.06479934
  -0.34927191 -0.79767357]
 [ 0.58956369 -0.09332226 -0.93876655  0.28143315  0.55076179  0.885

8. Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в 
діапазоні від 1 до 5 та знайдіть їх добуток.


In [16]:
matrix_9x9_a = np.random.randint(1, 6, (9, 9))
matrix_9x9_b = np.random.randint(1, 6, (9, 9))

product_9x9 = np.dot(matrix_9x9_a, matrix_9x9_b)
print("Матриця A:\n", matrix_9x9_a)
print("Матриця B:\n", matrix_9x9_b)
print("Добуток матриць A і B:\n", product_9x9)

9. Створіть дві матриці розміром 10x10, заповніть їх випадковими дійсними числами в 
діапазоні від -2 до 2 та знайдіть їх добуток.

In [17]:
matrix_10x10_a = np.random.uniform(-2, 2, (10, 10))
matrix_10x10_b = np.random.uniform(-2, 2, (10, 10))

In [18]:
product_10x10 = np.dot(matrix_10x10_a, matrix_10x10_b)
print("Матриця A:\n", matrix_10x10_a)
print("Матриця B:\n", matrix_10x10_b)
print("Добуток матриць A і B:\n", product_10x10)

Матриця A:
 [[-1.18381645 -1.80189212  0.85129932 -0.16372594  1.09406928  0.13241018
   0.80213666 -1.30022642 -1.49070827  0.13706338]
 [-1.94183307 -0.05626668  0.18092957 -0.54956074 -1.88689502 -0.09908649
   0.70785623 -0.81522084  1.02057953  1.10299792]
 [ 1.12057281 -1.13757482  0.06304619 -1.9125333  -0.03410105  1.08035285
  -1.4529789  -1.5425444  -1.97307077 -0.98890376]
 [-0.57880633 -1.88463791  1.20442825  1.71175837  0.58660184 -0.47106972
  -0.31900025  1.29826791 -1.01530464 -0.90369991]
 [ 0.53552772 -1.39497398  1.38778712 -1.50665684 -1.80594844 -0.98759565
  -0.64062762 -1.51070628 -1.80867355  0.28028784]
 [ 0.76770258  0.92593955  1.26306845  0.51019916  0.99283157  1.35330458
  -1.89590166 -1.74145721  1.66056072  1.74555114]
 [-1.35436288 -1.41700575 -1.22222057 -1.47507063  1.66560742  1.42524783
   1.71629817 -0.3161646  -0.36594505 -0.36470803]
 [-1.91935824  1.05302373  0.61794206 -1.18956134 -0.12636013 -1.75357884
  -1.26597306  0.14924461 -1.74657406 -

10. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в 
діапазоні від 1 до 10 та знайдіть різницю їх елементів.


In [19]:
matrix_2x2_int_a = np.random.randint(1, 11, (2, 2))
matrix_2x2_int_b = np.random.randint(1, 11, (2, 2))

In [20]:
difference_2x2_int = matrix_2x2_int_a - matrix_2x2_int_b
print("Матриця A:\n", matrix_2x2_int_a)
print("Матриця B:\n", matrix_2x2_int_b)
print("Різниця матриць A і B:\n", difference_2x2_int)

Матриця A:
 [[7 6]
 [9 9]]
Матриця B:
 [[7 4]
 [6 1]]
Різниця матриць A і B:
 [[0 2]
 [3 8]]
